name: sangjishik
description: My personal blog

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  animated_text_kit: ^4.2.2
  flextras: ^1.0.0
  go_router: ^6.0.1
  http: ^0.13.5
  shared_preferences: ^2.0.15
  sized_context: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: BeautifulPeople
      fonts:
        - asset: assets/fonts/BeautifulPeoplePersonalUse-dE0g.ttf
